# Mileage Prediction Using Various Machine Learning Techniques

### 1. Load the Dataset and Preprocessing

In [1]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

file_path = 'mileage (1).csv'
data = pd.read_csv(file_path)

imputer = SimpleImputer(strategy='median')
data['horsepower'] = imputer.fit_transform(data[['horsepower']])

data = pd.get_dummies(data, columns=['origin'], drop_first=True)
data = data.drop(columns=['name'])

X = data.drop(columns=['mpg'])
y = data['mpg']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### 2. Define a Function to Evaluate Model Performance

In [2]:

def evaluate_model(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    mae = mean_absolute_error(y_test, predictions)
    mse = mean_squared_error(y_test, predictions)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, predictions)
    return mae, mse, rmse, r2

### 3. Train and Evaluate Different Machine Learning Models

In [3]:

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.svm import SVR

model_performance = {}

lr_model = LinearRegression()
lr_results = evaluate_model(lr_model, X_train, X_test, y_train, y_test)
model_performance['Linear Regression'] = lr_results

dt_model = DecisionTreeRegressor(random_state=42)
dt_results = evaluate_model(dt_model, X_train, X_test, y_train, y_test)
model_performance['Decision Tree Regressor'] = dt_results

rf_model = RandomForestRegressor(random_state=42)
rf_results = evaluate_model(rf_model, X_train, X_test, y_train, y_test)
model_performance['Random Forest Regressor'] = rf_results

svr_model = SVR()
svr_results = evaluate_model(svr_model, X_train, X_test, y_train, y_test)
model_performance['Support Vector Regressor'] = svr_results

gb_model = GradientBoostingRegressor(random_state=42)
gb_results = evaluate_model(gb_model, X_train, X_test, y_train, y_test)
model_performance['Gradient Boosting Regressor'] = gb_results

performance_df = pd.DataFrame(model_performance, index=['MAE', 'MSE', 'RMSE', 'R2'])
performance_df

,Linear Regression,Decision Tree Regressor,Random Forest Regressor,Support Vector Regressor,Gradient Boosting Regressor
MAE,2.288159,2.241250,1.582338,2.789674,1.766858
MSE,8.338657,11.342375,4.615338,13.744208,5.585932
RMSE,2.887673,3.367844,2.148334,3.707318,2.363458
R2,0.844910,0.789044,0.914159,0.744372,0.896107

### 4. Analyze and Compare Model Performance

In [4]:

performance_df

,Linear Regression,Decision Tree Regressor,Random Forest Regressor,Support Vector Regressor,Gradient Boosting Regressor
MAE,2.288159,2.241250,1.582338,2.789674,1.766858
MSE,8.338657,11.342375,4.615338,13.744208,5.585932
RMSE,2.887673,3.367844,2.148334,3.707318,2.363458
R2,0.844910,0.789044,0.914159,0.744372,0.896107

### 5. Conclusion


Based on the evaluation metrics, the **Random Forest Regressor** performs the best, with the lowest MAE, MSE, and RMSE values, and the highest R² value. This makes it the most suitable model for predicting mileage in this dataset.